make tests/userprog/rox-simple.result
make tests/userprog/rox-child.result
make tests/userprog/rox-multichild.result
make tests/filesys/base/lg-create.result
make tests/filesys/base/lg-full.result
make tests/filesys/base/lg-seq-block.result
make tests/filesys/base/lg-seq-random.result
make tests/filesys/base/sm-create.result
make tests/filesys/base/sm-full.result
make tests/filesys/base/sm-random.result
make tests/filesys/base/sm-seq-block.result
make tests/filesys/base/sm-seq-random.result
make tests/filesys/base/syn-read.result
make tests/filesys/base/syn-remove.result
make tests/filesys/base/syn-write.result